version: 0.2

phases:
  pre_build:
    commands:
      - echo 'pre build'
  build:
    commands:
      - echo 'python -m unittest discover -s my-api'
artifacts:
  files: 
    - '**/*'
  base-directory: flaks_on_elasticbeanstalk